### ISSUE TITLE
Could not initialize GLFW

### ISSUE THREAD

**Issue by ROIAF** [wjakob/instant-meshes#21] opened 2016-02-13 18:29 UTC
Just tried to use for the first time after downloading and when the window opens, it gives a "GLFW error 65544: No monitors found" error.  The error box pops up with Caught a fatal error: Could not initialize GLFW!

Any suggestions?

**Comment by wjakob** [comment] 2016-02-13 18:56
Duplicate of #13.

**Closed by wjakob** 2016-02-13 18:56 UTC

**Comment by wjakob** [comment] 2016-02-14 12:03
Either way, this is a configuration issue with GLFW (http://www.glfw.org/) in your issue and not at all related to Instant Meshes. It's not something that can be solved here.
