### ISSUE TITLE
Save dialog appears behind application under Ubuntu

### ISSUE THREAD

**Issue by HolySmokesBatman** [wjakob/instant-meshes#4] opened 2015-11-13 20:50 UTC
The Export Mesh/Save dialog appears to pop up behind the application under Ubuntu, making it appear that the application has hung, especially if the application is full screen when the Save is selected.  I ran the app from a Terminal window under Ubuntu 14.04 64-bit using the downloadable binaries (not locally compiled).

**Comment by wjakob** [comment] 2015-11-17 10:08
hi -- I just tested on Ubuntu and can't reproduce this behavior. The save/load dialog is realized using ``zenity``, which detects the application that started it so that it can launch in front of that. It works for me in both full screen and windowed mode on 14.04 (trusty).

**Comment by wjakob** [comment] 2015-11-17 10:08
(Of course, you can alt-tab to a different application, which will mess up the focus order -- but it is initially correct)

**Comment by wjakob** [comment] 2015-11-19 07:20
Closing this ticket (insufficient info to reproduce on same platform) -- feel free to reopen if you have more details.

**Closed by wjakob** 2015-11-19 07:20 UTC
