### ISSUE TITLE
Tool Crash - Win10

### ISSUE THREAD

**Issue by shakthi666** [wjakob/instant-meshes#22] opened 2016-02-18 08:45 UTC
Hi,

I am working on a model of around 700K poly and the tool works fine until i try to export the final mesh.

Am i missing something?

Thank You

**Comment by wjakob** [comment] 2016-02-18 08:49
To have something reproducible on our end, you'll need to submit your mesh and the exact sequence of steps done.

**Comment by shakthi666** [comment] 2016-02-19 07:48
http://we.tl/KI4xyAVMcq  this is the model and below is the screen shot
until i try to export it.
The output file keeps building in size and the tool crashes when the size
is around 6GB.

[image: Capture.JPG][image: Capture1.JPG]

**Comment by wjakob** [comment] 2016-02-19 07:58
Maybe your machine simply runs out of memory? During extraction, a fair bit of additional memory is required.

**Comment by shakthi666** [comment] 2016-02-19 16:02
I doubt it.. My config has 32GB DDR5 ram,  and instant meshes is the only
tool I had open.

**Comment by liuaddie** [comment] 2016-02-23 10:44
I have same problem too. I imported a 400mb obj (exported from Maya), after paint the position field in Instant Meshes, saved a 3.8GB ply file.

Originally "Target vertex count" is 312.50K, and it have same case as "shakthi666". The output file keeps building in size and I stopped it at >30GB.

Then I try different "Target vertex count", 181K is ok for export obj, but when it larger then 181K, it will keeps building in size.

Hope it is useful for you, @shakthi666.

**Comment by liuaddie** [comment] 2016-02-23 10:51
@wjakob , I am looking into the code in "meshio". trying to track the problem and report. Thanks for your great work~ +1

**Comment by shakthi666** [comment] 2016-02-23 11:40
That solved.. thank you .. !!

**Comment by carlvieriste** [comment] 2016-06-09 18:45
Hi @wjakob, I debugged the software and found a fix. We have this bug even with a target vertex count of 50K.
The problem is [`write_obj()` in `meshio.cpp`](https://github.com/wjakob/instant-meshes/blob/master/src/meshio.cpp#L603). An irregular face is traversed by going through the vertex chain. The `while(true)` loop breaks when it has gone back to the first vertex.
Sometimes, it goes back to a vertex it has already seen, other than the first vertex. Result: it loops forever, never getting to the first vertex.

My first try at a fix was this: we keep the vertex indices in a set. When we go back to a vertex that was already seen (but that is not the first), we break the loop. That solution was not right, since it produced faces with only two vertices.

The working solution is the same as above, except that when we detect that we're going back to an already seen vertex, **we write it to the file** before breaking the loop.

Here is the section of `write_obj()` after modifications:
```c++
for (auto item : irregular) {
        auto face = item.second;
        uint32_t v = face.second.begin()->first, first = v;
        std::set<uint32_t> v_set; // NEW
        bool abort(false); // NEW       
        os << "f ";
        while (true) {
            uint32_t idx = v + 1;
            os << idx;
            if (Nf.size() > 0)
                idx = face.first + 1;
            os << "//" << idx << " ";

            if (abort) break; // NEW

            v_set.insert(v);
            v = face.second[v];
            if (v == first)
                break;
            else if (v_set.find(v) != v_set.end()) // NEW
            {
                cout << "Face does not loop back to first vertex! Aborting face. Num vertices: " << v_set.size() << endl;
                abort = true;
            }
        }
        os << endl;
    }
```

**Comment by wjakob** [comment] 2016-11-03 13:02
@carlvieriste: Thank you very much for tracking this down, and sorry that it took me so long to get back. I committed a modified version of your patch.

**Closed by wjakob** 2016-11-03 13:02 UTC
